import { Injectable } from '@nestjs/common';
const mysql = require('mysql2/promise');

@Injectable()
export class QueryService {
  async creatingDatabase() {
    const mainconnection = await mysql.createConnection({
      host: 'localhost',
      user: 'root',
      password: '',
    });
    // Create the database if it doesn't exist
    try {
      await mainconnection.execute(
        `CREATE DATABASE IF NOT EXISTS darsoftTechnical CHARACTER SET utf8 COLLATE utf8_general_ci`,
      );
    } catch (err) {
      console.log('Error creating database:', err);
    }
  }

  async creatingCountries(){
    try {
      // creating all countries 
      const connection = await mysql.createConnection({
      host: "localhost",
      user: "root",
      password: "",
      database: "darsoftTechnical",
    });
    const [rows, fields] = await connection.execute(
      'SELECT countrieId FROM countries LIMIT 1'
    );
    if (rows.length === 0) {
      await connection.execute(`
      INSERT INTO countries (name) VALUES
      ('Afghanistan'),
      ('Albania'),
      ('Algeria'),
      ('Andorra'),
      ('Angola'),
      ('Antigua and Barbuda'),
      ('Argentina'),
      ('Armenia'),
      ('Australia'),
      ('Austria'),
      ('Azerbaijan'),
      ('Bahamas'),
      ('Bahrain'),
      ('Bangladesh'),
      ('Barbados'),
      ('Belarus'),
      ('Belgium'),
      ('Belize'),
      ('Benin'),
      ('Bhutan'),
      ('Bolivia'),
      ('Bosnia and Herzegovina'),
      ('Botswana'),
      ('Brazil'),
      ('Brunei'),
      ('Bulgaria'),
      ('Burkina Faso'),
      ('Burundi'),
      ('Cabo Verde'),
      ('Cambodia'),
      ('Cameroon'),
      ('Canada'),
      ('Central African Republic'),
      ('Chad'),
      ('Chile'),
      ('China'),
      ('Colombia'),
      ('Comoros'),
      ('Congo, Democratic Republic of the'),
      ('Congo, Republic of the'),
      ('Costa Rica'),
      ('Croatia'),
      ('Cuba'),
      ('Cyprus'),
      ('Czech Republic'),
      ('Denmark'),
      ('Djibouti'),
      ('Dominica'),
      ('Dominican Republic'),
      ('Ecuador'),
      ('Egypt'),
      ('El Salvador'),
      ('Equatorial Guinea'),
      ('Eritrea'),
      ('Estonia'),
      ('Eswatini'),
      ('Ethiopia'),
      ('Fiji'),
      ('Finland'),
      ('France'),
      ('Gabon'),
      ('Gambia'),
      ('Georgia'),
      ('Germany'),
      ('Ghana'),
      ('Greece'),
      ('Grenada'),
      ('Guatemala'),
      ('Guinea'),
      ('Guinea-Bissau'),
      ('Guyana'),
      ('Haiti'),
      ('Honduras'),
      ('Hungary'),
      ('Iceland'),
      ('India'),
      ('Indonesia'),
      ('Iran'),
      ('Iraq'),
      ('Ireland'),
      ('Palestine'),
      ('Italy'),
      ('Jamaica'),
      ('Japan'),
      ('Jordan'),
      ('Kazakhstan'),
      ('Kenya'),
      ('Kiribati'),
      ('Korea, North'),
      ('Korea, South'),
      ('Kosovo'),
      ('Kuwait'),
      ('Kyrgyzstan'),
      ('Laos'),
      ('Latvia'),
      ('Lebanon'),
      ('Lesotho'),
      ('Liberia'),
      ('Libya'),
      ('Liechtenstein'),
      ('Lithuania'),
      ('Luxembourg'),
      ('Madagascar'),
      ('Malawi'),
      ('Malaysia'),
      ('Maldives'),
      ('Mali'),
      ('Malta'),
      ('Marshall Islands'),
      ('Mauritania'),
      ('Mauritius'),
      ('Mexico'),
      ('Micronesia'),
      ('Moldova'),
      ('Monaco'),
      ('Mongolia'),
      ('Montenegro'),
      ('Morocco'),
      ('Mozambique'),
      ('Myanmar (Burma)'),
      ('Namibia'),
      ('Nauru'),
      ('Nepal'),
      ('Netherlands'),
      ('New Zealand'),
      ('Nicaragua'),
      ('Niger'),
      ('Nigeria'),
      ('North Macedonia'),
      ('Norway'),
      ('Oman'),
      ('Pakistan'),
      ('Palau'),
      ('Panama'),
      ('Papua New Guinea'),
      ('Paraguay'),
      ('Peru'),
      ('Philippines'),
      ('Poland'),
      ('Portugal'),
      ('Qatar'),
      ('Romania'),
      ('Russia'),
      ('Rwanda'),
      ('Saint Kitts and Nevis'),
      ('Saint Lucia'),
      ('Saint Vincent and the Grenadines'),
      ('Samoa'),
      ('San Marino'),
      ('Sao Tome and Principe'),
      ('Saudi Arabia'),
      ('Senegal'),
      ('Serbia'),
      ('Seychelles'),
      ('Sierra Leone'),
      ('Singapore'),
      ('Slovakia'),
      ('Slovenia'),
      ('Solomon Islands'),
      ('Somalia'),
      ('South Africa'),
      ('South Sudan'),
      ('Spain'),
      ('Sri Lanka'),
      ('Sudan'),
      ('Suriname'),
      ('Sweden'),
      ('Switzerland'),
      ('Syria'),
      ('Taiwan'),
      ('Tajikistan'),
      ('Tanzania'),
      ('Thailand'),
      ('Timor-Leste'),
      ('Togo'),
      ('Tonga'),
      ('Trinidad and Tobago'),
      ('Tunisia'),
      ('Turkey'),
      ('Turkmenistan'),
      ('Tuvalu'),
      ('Uganda'),
      ('Ukraine'),
      ('United Arab Emirates'),
      ('United Kingdom'),
      ('United States'),
      ('Uruguay'),
      ('Uzbekistan'),
      ('Vanuatu'),
      ('Vatican City'),
      ('Venezuela'),
      ('Vietnam'),
      ('Yemen'),
      ('Zambia'),
      ('Zimbabwe');
      
    `);
    }
    } catch (err) {
      console.log('Error creating database:', err);
    }

  }
}
